FROM postgres:11.16

ENV POSTGRES_DB flexberryservicebus
ENV POSTGRES_USER flexberryservicebususer
ENV POSTGRES_PASSWORD jhv

COPY SQL/create_tables.sql /docker-entrypoint-initdb.d/
COPY SQL/insert_records.sql /docker-entrypoint-initdb.d/