FROM mcr.microsoft.com/dotnet/sdk:3.1 as servicebuild

COPY . /WORKDIR
WORKDIR /WORKDIR

RUN \
 dotnet restore WCFRecipient1.ConsoleHost.csproj;\
 dotnet build WCFRecipient1.ConsoleHost.csproj -c Debug;\
 dotnet publish WCFRecipient1.ConsoleHost.csproj -c Debug -o out -f netcoreapp3.1

FROM mcr.microsoft.com/dotnet/aspnet:3.1

WORKDIR /app

COPY --from=servicebuild /WORKDIR/out ./
ENTRYPOINT ["dotnet", "WCFRecipient1.ConsoleHost.dll"]