FROM mcr.microsoft.com/dotnet/sdk:3.1 as servicebuild

COPY . /WORKDIR
WORKDIR /WORKDIR

RUN \
 dotnet restore RestRecipient.ConsoleHost.csproj;\
 dotnet build RestRecipient.ConsoleHost.csproj -c Debug;\
 dotnet publish RestRecipient.ConsoleHost.csproj -c Debug -o out -f netcoreapp3.1

FROM mcr.microsoft.com/dotnet/aspnet:3.1

WORKDIR /app

COPY --from=servicebuild /WORKDIR/out ./
ENTRYPOINT ["dotnet", "RestRecipient.ConsoleHost.dll"]